name: build and deploy

on: 
  push:
    branches: [ main ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: pandoc/latex:latest
    steps:
      - uses: actions/checkout@v4

      - name: Convert Markdown to HTML
        run: >
          pandoc index.md 
          -f markdown 
          -t html 
          --standalone
          --css=custom.css
          -o index.html

      - name: Upload HTML to GitHub Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: .

      - uses: actions/deploy-pages@v4

